backend:
  name: github
  repo: mustech129/blog   # your GitHub repo
  branch: main            # or your deployment branch
  auth_type: implicit     # must be implicit for Netlify
  base_url: ""            # leave empty for Netlify


media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
