backend:
  name: github
  repo: mustech129/blog
  branch: main
  auth_type: "implicit"
  client_id: "Ov23liqgsTF2XLYholLJ"
  client_secret: "30dd7df7f12f062b397b9480760550cc0f8be1ce"

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
