backend:
  name: github
  repo: mustech129/blog  # Replace with your GitHub username and repo
  branch: main                  # The branch where posts will be saved
media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
