backend:
  name: github
  repo: mustech129/novablog
  branch: jekyll-setup
media_folder: "assets/uploads"
public_folder: "/assets/uploads"
collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
